name: flutter_docs_analyzer
description: A simple command-line application.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  surveyor:
    git:
      url: git@github.com:pq/surveyor.git
      ref: master
  analyzer: any

dev_dependencies:
  pedantic: ^1.9.0
